rm build-info.log
rm build-stats.log

echo bsp > build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" ..\Core\Src\bsp.c -D STM32F303x8 -D USE_FULL_LL_DRIVER -o ..\EWARM\Release\Obj\Core_13247989168731456611.dir --debug --endian=little --cpu=Cortex-M4 -e --warnings_are_errors --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I ..\EWARM/../Core/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\ -I ..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\ -I ..\EWARM/../Drivers/CMSIS/Include\ -Ohs --require_prototypes >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" ..\Core\Src\bsp.c -D STM32F303x8 -D USE_FULL_LL_DRIVER -o ..\EWARM\Debug\Obj\Core_13247989168731456611.dir --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling --debug --endian=little --cpu=Cortex-M4 -e --warnings_are_errors --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I ..\EWARM/../Core/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\ -I ..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\ -I ..\EWARM/../Drivers/CMSIS/Include\ -On --require_prototypes >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" ..\Core\Src\bsp.c -D STM32F303x8 -D USE_FULL_LL_DRIVER -D ENABLE_UART_DEBUGGING -o ..\EWARM\Printf\Obj\Core_13247989168731456611.dir --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling --debug --endian=little --cpu=Cortex-M4 -e --warnings_are_errors --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I ..\EWARM/../Core/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\ -I ..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\ -I ..\EWARM/../Drivers/CMSIS/Include\ -On --require_prototypes >> build-info.log

echo button_handler >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" ..\Core\Src\button_handler.c -D STM32F303x8 -D USE_FULL_LL_DRIVER -o ..\EWARM\Release\Obj\Core_13247989168731456611.dir --debug --endian=little --cpu=Cortex-M4 -e --warnings_are_errors --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I ..\EWARM/../Core/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\ -I ..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\ -I ..\EWARM/../Drivers/CMSIS/Include\ -Ohs --require_prototypes >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" ..\Core\Src\button_handler.c -D STM32F303x8 -D USE_FULL_LL_DRIVER -o ..\EWARM\Debug\Obj\Core_13247989168731456611.dir --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling --debug --endian=little --cpu=Cortex-M4 -e --warnings_are_errors --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I ..\EWARM/../Core/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\ -I ..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\ -I ..\EWARM/../Drivers/CMSIS/Include\ -On --require_prototypes >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" ..\Core\Src\button_handler.c -D STM32F303x8 -D USE_FULL_LL_DRIVER -D ENABLE_UART_DEBUGGING -o ..\EWARM\Printf\Obj\Core_13247989168731456611.dir --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling --debug --endian=little --cpu=Cortex-M4 -e --warnings_are_errors --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I ..\EWARM/../Core/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\ -I ..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\ -I ..\EWARM/../Drivers/CMSIS/Include\ -On --require_prototypes >> build-info.log

echo delay_handler >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" ..\Core\Src\delay_handler.c -D STM32F303x8 -D USE_FULL_LL_DRIVER -o ..\EWARM\Release\Obj\Core_13247989168731456611.dir --debug --endian=little --cpu=Cortex-M4 -e --warnings_are_errors --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I ..\EWARM/../Core/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\ -I ..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\ -I ..\EWARM/../Drivers/CMSIS/Include\ -Ohs --require_prototypes >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" ..\Core\Src\delay_handler.c -D STM32F303x8 -D USE_FULL_LL_DRIVER -o ..\EWARM\Debug\Obj\Core_13247989168731456611.dir --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling --debug --endian=little --cpu=Cortex-M4 -e --warnings_are_errors --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I ..\EWARM/../Core/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\ -I ..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\ -I ..\EWARM/../Drivers/CMSIS/Include\ -On --require_prototypes >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" ..\Core\Src\delay_handler.c -D STM32F303x8 -D USE_FULL_LL_DRIVER -D ENABLE_UART_DEBUGGING -o ..\EWARM\Printf\Obj\Core_13247989168731456611.dir --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling --debug --endian=little --cpu=Cortex-M4 -e --warnings_are_errors --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I ..\EWARM/../Core/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\ -I ..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\ -I ..\EWARM/../Drivers/CMSIS/Include\ -On --require_prototypes >> build-info.log

echo gpio >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" ..\Core\Src\gpio.c -D STM32F303x8 -D USE_FULL_LL_DRIVER -o ..\EWARM\Release\Obj\Core_13247989168731456611.dir --debug --endian=little --cpu=Cortex-M4 -e --warnings_are_errors --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I ..\EWARM/../Core/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\ -I ..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\ -I ..\EWARM/../Drivers/CMSIS/Include\ -Ohs --require_prototypes >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" ..\Core\Src\gpio.c -D STM32F303x8 -D USE_FULL_LL_DRIVER -o ..\EWARM\Debug\Obj\Core_13247989168731456611.dir --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling --debug --endian=little --cpu=Cortex-M4 -e --warnings_are_errors --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I ..\EWARM/../Core/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\ -I ..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\ -I ..\EWARM/../Drivers/CMSIS/Include\ -On --require_prototypes >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" ..\Core\Src\gpio.c -D STM32F303x8 -D USE_FULL_LL_DRIVER -D ENABLE_UART_DEBUGGING -o ..\EWARM\Printf\Obj\Core_13247989168731456611.dir --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling --debug --endian=little --cpu=Cortex-M4 -e --warnings_are_errors --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I ..\EWARM/../Core/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\ -I ..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\ -I ..\EWARM/../Drivers/CMSIS/Include\ -On --require_prototypes >> build-info.log

echo logger >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" ..\Core\Src\logger.c -D STM32F303x8 -D USE_FULL_LL_DRIVER -o ..\EWARM\Release\Obj\Core_13247989168731456611.dir --debug --endian=little --cpu=Cortex-M4 -e --warnings_are_errors --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I ..\EWARM/../Core/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\ -I ..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\ -I ..\EWARM/../Drivers/CMSIS/Include\ -Ohs --require_prototypes >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" ..\Core\Src\logger.c -D STM32F303x8 -D USE_FULL_LL_DRIVER -o ..\EWARM\Debug\Obj\Core_13247989168731456611.dir --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling --debug --endian=little --cpu=Cortex-M4 -e --warnings_are_errors --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I ..\EWARM/../Core/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\ -I ..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\ -I ..\EWARM/../Drivers/CMSIS/Include\ -On --require_prototypes >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" ..\Core\Src\logger.c -D STM32F303x8 -D USE_FULL_LL_DRIVER -D ENABLE_UART_DEBUGGING -o ..\EWARM\Printf\Obj\Core_13247989168731456611.dir --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling --debug --endian=little --cpu=Cortex-M4 -e --warnings_are_errors --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I ..\EWARM/../Core/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\ -I ..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\ -I ..\EWARM/../Drivers/CMSIS/Include\ -On --require_prototypes >> build-info.log

echo main >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" ..\Core\Src\main.c -D STM32F303x8 -D USE_FULL_LL_DRIVER -o ..\EWARM\Release\Obj\Core_13247989168731456611.dir --debug --endian=little --cpu=Cortex-M4 -e --warnings_are_errors --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I ..\EWARM/../Core/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\ -I ..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\ -I ..\EWARM/../Drivers/CMSIS/Include\ -Ohs --require_prototypes >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" ..\Core\Src\main.c -D STM32F303x8 -D USE_FULL_LL_DRIVER -o ..\EWARM\Debug\Obj\Core_13247989168731456611.dir --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling --debug --endian=little --cpu=Cortex-M4 -e --warnings_are_errors --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I ..\EWARM/../Core/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\ -I ..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\ -I ..\EWARM/../Drivers/CMSIS/Include\ -On --require_prototypes >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" ..\Core\Src\main.c -D STM32F303x8 -D USE_FULL_LL_DRIVER -D ENABLE_UART_DEBUGGING -o ..\EWARM\Printf\Obj\Core_13247989168731456611.dir --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling --debug --endian=little --cpu=Cortex-M4 -e --warnings_are_errors --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I ..\EWARM/../Core/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\ -I ..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\ -I ..\EWARM/../Drivers/CMSIS/Include\ -On --require_prototypes >> build-info.log

echo my_printf >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" ..\Core\Src\my_printf.c -D STM32F303x8 -D USE_FULL_LL_DRIVER -o ..\EWARM\Release\Obj\Core_13247989168731456611.dir --debug --endian=little --cpu=Cortex-M4 -e --warnings_are_errors --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I ..\EWARM/../Core/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\ -I ..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\ -I ..\EWARM/../Drivers/CMSIS/Include\ -Ohs --require_prototypes >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" ..\Core\Src\my_printf.c -D STM32F303x8 -D USE_FULL_LL_DRIVER -o ..\EWARM\Debug\Obj\Core_13247989168731456611.dir --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling --debug --endian=little --cpu=Cortex-M4 -e --warnings_are_errors --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I ..\EWARM/../Core/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\ -I ..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\ -I ..\EWARM/../Drivers/CMSIS/Include\ -On --require_prototypes >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" ..\Core\Src\my_printf.c -D STM32F303x8 -D USE_FULL_LL_DRIVER -D ENABLE_UART_DEBUGGING -o ..\EWARM\Printf\Obj\Core_13247989168731456611.dir --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling --debug --endian=little --cpu=Cortex-M4 -e --warnings_are_errors --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I ..\EWARM/../Core/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\ -I ..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\ -I ..\EWARM/../Drivers/CMSIS/Include\ -On --require_prototypes >> build-info.log

echo pwm_handler >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" ..\Core\Src\pwm_handler.c -D STM32F303x8 -D USE_FULL_LL_DRIVER -o ..\EWARM\Release\Obj\Core_13247989168731456611.dir --debug --endian=little --cpu=Cortex-M4 -e --warnings_are_errors --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I ..\EWARM/../Core/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\ -I ..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\ -I ..\EWARM/../Drivers/CMSIS/Include\ -Ohs --require_prototypes >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" ..\Core\Src\pwm_handler.c -D STM32F303x8 -D USE_FULL_LL_DRIVER -o ..\EWARM\Debug\Obj\Core_13247989168731456611.dir --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling --debug --endian=little --cpu=Cortex-M4 -e --warnings_are_errors --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I ..\EWARM/../Core/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\ -I ..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\ -I ..\EWARM/../Drivers/CMSIS/Include\ -On --require_prototypes >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" ..\Core\Src\pwm_handler.c -D STM32F303x8 -D USE_FULL_LL_DRIVER -D ENABLE_UART_DEBUGGING -o ..\EWARM\Printf\Obj\Core_13247989168731456611.dir --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling --debug --endian=little --cpu=Cortex-M4 -e --warnings_are_errors --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I ..\EWARM/../Core/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\ -I ..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\ -I ..\EWARM/../Drivers/CMSIS/Include\ -On --require_prototypes >> build-info.log

echo stm32f3xx_it >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" ..\Core\Src\stm32f3xx_it.c -D STM32F303x8 -D USE_FULL_LL_DRIVER -o ..\EWARM\Release\Obj\Core_13247989168731456611.dir --debug --endian=little --cpu=Cortex-M4 -e --warnings_are_errors --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I ..\EWARM/../Core/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\ -I ..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\ -I ..\EWARM/../Drivers/CMSIS/Include\ -Ohs --require_prototypes >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" ..\Core\Src\stm32f3xx_it.c -D STM32F303x8 -D USE_FULL_LL_DRIVER -o ..\EWARM\Debug\Obj\Core_13247989168731456611.dir --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling --debug --endian=little --cpu=Cortex-M4 -e --warnings_are_errors --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I ..\EWARM/../Core/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\ -I ..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\ -I ..\EWARM/../Drivers/CMSIS/Include\ -On --require_prototypes >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" ..\Core\Src\stm32f3xx_it.c -D STM32F303x8 -D USE_FULL_LL_DRIVER -D ENABLE_UART_DEBUGGING -o ..\EWARM\Printf\Obj\Core_13247989168731456611.dir --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling --debug --endian=little --cpu=Cortex-M4 -e --warnings_are_errors --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I ..\EWARM/../Core/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\ -I ..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\ -I ..\EWARM/../Drivers/CMSIS/Include\ -On --require_prototypes >> build-info.log

echo system_stm32f3xx >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" ..\Core\Src\system_stm32f3xx.c -D STM32F303x8 -D USE_FULL_LL_DRIVER -o ..\EWARM\Release\Obj\CMSIS_6603591812247902717.dir --debug --endian=little --cpu=Cortex-M4 -e --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I ..\EWARM/../Core/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\ -I ..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\ -I ..\EWARM/../Drivers/CMSIS/Include\ -Ohs >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" ..\Core\Src\system_stm32f3xx.c -D STM32F303x8 -D USE_FULL_LL_DRIVER -o ..\EWARM\Debug\Obj\CMSIS_6603591812247902717.dir --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling --debug --endian=little --cpu=Cortex-M4 -e --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I ..\EWARM/../Core/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\ -I ..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\ -I ..\EWARM/../Drivers/CMSIS/Include\ -On >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" ..\Core\Src\system_stm32f3xx.c -D STM32F303x8 -D USE_FULL_LL_DRIVER -D ENABLE_UART_DEBUGGING -o ..\EWARM\Printf\Obj\CMSIS_6603591812247902717.dir --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling --debug --endian=little --cpu=Cortex-M4 -e --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I ..\EWARM/../Core/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\ -I ..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\ -I ..\EWARM/../Drivers/CMSIS/Include\ -On >> build-info.log

echo thermistor_handler >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" ..\Core\Src\thermistor_handler.c -D STM32F303x8 -D USE_FULL_LL_DRIVER -o ..\EWARM\Release\Obj\Core_13247989168731456611.dir --debug --endian=little --cpu=Cortex-M4 -e --warnings_are_errors --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I ..\EWARM/../Core/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\ -I ..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\ -I ..\EWARM/../Drivers/CMSIS/Include\ -Ohs --require_prototypes >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" ..\Core\Src\thermistor_handler.c -D STM32F303x8 -D USE_FULL_LL_DRIVER -o ..\EWARM\Debug\Obj\Core_13247989168731456611.dir --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling --debug --endian=little --cpu=Cortex-M4 -e --warnings_are_errors --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I ..\EWARM/../Core/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\ -I ..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\ -I ..\EWARM/../Drivers/CMSIS/Include\ -On --require_prototypes >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" ..\Core\Src\thermistor_handler.c -D STM32F303x8 -D USE_FULL_LL_DRIVER -D ENABLE_UART_DEBUGGING -o ..\EWARM\Printf\Obj\Core_13247989168731456611.dir --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling --debug --endian=little --cpu=Cortex-M4 -e --warnings_are_errors --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I ..\EWARM/../Core/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\ -I ..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\ -I ..\EWARM/../Drivers/CMSIS/Include\ -On --require_prototypes >> build-info.log

echo tim >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" ..\Core\Src\tim.c -D STM32F303x8 -D USE_FULL_LL_DRIVER -o ..\EWARM\Release\Obj\Core_13247989168731456611.dir --debug --endian=little --cpu=Cortex-M4 -e --warnings_are_errors --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I ..\EWARM/../Core/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\ -I ..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\ -I ..\EWARM/../Drivers/CMSIS/Include\ -Ohs --require_prototypes >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" ..\Core\Src\tim.c -D STM32F303x8 -D USE_FULL_LL_DRIVER -o ..\EWARM\Debug\Obj\Core_13247989168731456611.dir --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling --debug --endian=little --cpu=Cortex-M4 -e --warnings_are_errors --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I ..\EWARM/../Core/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\ -I ..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\ -I ..\EWARM/../Drivers/CMSIS/Include\ -On --require_prototypes >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" ..\Core\Src\tim.c -D STM32F303x8 -D USE_FULL_LL_DRIVER -D ENABLE_UART_DEBUGGING -o ..\EWARM\Printf\Obj\Core_13247989168731456611.dir --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling --debug --endian=little --cpu=Cortex-M4 -e --warnings_are_errors --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I ..\EWARM/../Core/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\ -I ..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\ -I ..\EWARM/../Drivers/CMSIS/Include\ -On --require_prototypes >> build-info.log

echo usart >> build-info.log
REM USART only used for uart debugging
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" ..\Core\Src\usart.c -D STM32F303x8 -D USE_FULL_LL_DRIVER -D ENABLE_UART_DEBUGGING -o ..\EWARM\Printf\Obj\Core_13247989168731456611.dir --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling --debug --endian=little --cpu=Cortex-M4 -e --warnings_are_errors --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I ..\EWARM/../Core/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\ -I ..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\ -I ..\EWARM/../Drivers/CMSIS/Include\ -On --require_prototypes >> build-info.log

echo stm32f3xx_ll_dma >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" ..\Drivers\STM32F3xx_HAL_Driver\Src\stm32f3xx_ll_dma.c -D STM32F303x8 -D USE_FULL_LL_DRIVER -o ..\EWARM\Release\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir --debug --endian=little --cpu=Cortex-M4 -e --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I ..\EWARM/../Core/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\ -I ..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\ -I ..\EWARM/../Drivers/CMSIS/Include\ -Ohs >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" ..\Drivers\STM32F3xx_HAL_Driver\Src\stm32f3xx_ll_dma.c -D STM32F303x8 -D USE_FULL_LL_DRIVER -o ..\EWARM\Debug\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling --debug --endian=little --cpu=Cortex-M4 -e --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I ..\EWARM/../Core/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\ -I ..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\ -I ..\EWARM/../Drivers/CMSIS/Include\ -On >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" ..\Drivers\STM32F3xx_HAL_Driver\Src\stm32f3xx_ll_dma.c -D STM32F303x8 -D USE_FULL_LL_DRIVER -D ENABLE_UART_DEBUGGING -o ..\EWARM\Printf\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling --debug --endian=little --cpu=Cortex-M4 -e --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I ..\EWARM/../Core/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\ -I ..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\ -I ..\EWARM/../Drivers/CMSIS/Include\ -On >> build-info.log

echo stm32f3xx_ll_exti >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" ..\Drivers\STM32F3xx_HAL_Driver\Src\stm32f3xx_ll_exti.c -D STM32F303x8 -D USE_FULL_LL_DRIVER -o ..\EWARM\Release\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir --debug --endian=little --cpu=Cortex-M4 -e --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I ..\EWARM/../Core/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\ -I ..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\ -I ..\EWARM/../Drivers/CMSIS/Include\ -Ohs >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" ..\Drivers\STM32F3xx_HAL_Driver\Src\stm32f3xx_ll_exti.c -D STM32F303x8 -D USE_FULL_LL_DRIVER -o ..\EWARM\Debug\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling --debug --endian=little --cpu=Cortex-M4 -e --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I ..\EWARM/../Core/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\ -I ..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\ -I ..\EWARM/../Drivers/CMSIS/Include\ -On >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" ..\Drivers\STM32F3xx_HAL_Driver\Src\stm32f3xx_ll_exti.c -D STM32F303x8 -D USE_FULL_LL_DRIVER -D ENABLE_UART_DEBUGGING -o ..\EWARM\Printf\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling --debug --endian=little --cpu=Cortex-M4 -e --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I ..\EWARM/../Core/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\ -I ..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\ -I ..\EWARM/../Drivers/CMSIS/Include\ -On >> build-info.log

echo stm32f3xx_ll_gpio >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" ..\Drivers\STM32F3xx_HAL_Driver\Src\stm32f3xx_ll_gpio.c -D STM32F303x8 -D USE_FULL_LL_DRIVER -o ..\EWARM\Release\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir --debug --endian=little --cpu=Cortex-M4 -e --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I ..\EWARM/../Core/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\ -I ..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\ -I ..\EWARM/../Drivers/CMSIS/Include\ -Ohs >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" ..\Drivers\STM32F3xx_HAL_Driver\Src\stm32f3xx_ll_gpio.c -D STM32F303x8 -D USE_FULL_LL_DRIVER -o ..\EWARM\Debug\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling --debug --endian=little --cpu=Cortex-M4 -e --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I ..\EWARM/../Core/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\ -I ..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\ -I ..\EWARM/../Drivers/CMSIS/Include\ -On >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" ..\Drivers\STM32F3xx_HAL_Driver\Src\stm32f3xx_ll_gpio.c -D STM32F303x8 -D USE_FULL_LL_DRIVER -D ENABLE_UART_DEBUGGING -o ..\EWARM\Printf\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling --debug --endian=little --cpu=Cortex-M4 -e --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I ..\EWARM/../Core/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\ -I ..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\ -I ..\EWARM/../Drivers/CMSIS/Include\ -On >> build-info.log

echo stm32f3xx_ll_rcc >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" ..\Drivers\STM32F3xx_HAL_Driver\Src\stm32f3xx_ll_rcc.c -D STM32F303x8 -D USE_FULL_LL_DRIVER -o ..\EWARM\Release\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir --debug --endian=little --cpu=Cortex-M4 -e --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I ..\EWARM/../Core/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\ -I ..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\ -I ..\EWARM/../Drivers/CMSIS/Include\ -Ohs >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" ..\Drivers\STM32F3xx_HAL_Driver\Src\stm32f3xx_ll_rcc.c -D STM32F303x8 -D USE_FULL_LL_DRIVER -o ..\EWARM\Debug\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling --debug --endian=little --cpu=Cortex-M4 -e --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I ..\EWARM/../Core/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\ -I ..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\ -I ..\EWARM/../Drivers/CMSIS/Include\ -On >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" ..\Drivers\STM32F3xx_HAL_Driver\Src\stm32f3xx_ll_rcc.c -D STM32F303x8 -D USE_FULL_LL_DRIVER -D ENABLE_UART_DEBUGGING -o ..\EWARM\Printf\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling --debug --endian=little --cpu=Cortex-M4 -e --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I ..\EWARM/../Core/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\ -I ..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\ -I ..\EWARM/../Drivers/CMSIS/Include\ -On >> build-info.log

echo stm32f3xx_ll_tim >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" ..\Drivers\STM32F3xx_HAL_Driver\Src\stm32f3xx_ll_tim.c -D STM32F303x8 -D USE_FULL_LL_DRIVER -o ..\EWARM\Release\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir --debug --endian=little --cpu=Cortex-M4 -e --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I ..\EWARM/../Core/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\ -I ..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\ -I ..\EWARM/../Drivers/CMSIS/Include\ -Ohs >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" ..\Drivers\STM32F3xx_HAL_Driver\Src\stm32f3xx_ll_tim.c -D STM32F303x8 -D USE_FULL_LL_DRIVER -o ..\EWARM\Debug\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling --debug --endian=little --cpu=Cortex-M4 -e --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I ..\EWARM/../Core/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\ -I ..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\ -I ..\EWARM/../Drivers/CMSIS/Include\ -On >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" ..\Drivers\STM32F3xx_HAL_Driver\Src\stm32f3xx_ll_tim.c -D STM32F303x8 -D USE_FULL_LL_DRIVER -D ENABLE_UART_DEBUGGING -o ..\EWARM\Printf\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling --debug --endian=little --cpu=Cortex-M4 -e --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I ..\EWARM/../Core/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\ -I ..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\ -I ..\EWARM/../Drivers/CMSIS/Include\ -On >> build-info.log

echo stm32f3xx_ll_usart >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" ..\Drivers\STM32F3xx_HAL_Driver\Src\stm32f3xx_ll_usart.c -D STM32F303x8 -D USE_FULL_LL_DRIVER -o ..\EWARM\Release\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir --debug --endian=little --cpu=Cortex-M4 -e --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I ..\EWARM/../Core/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\ -I ..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\ -I ..\EWARM/../Drivers/CMSIS/Include\ -Ohs >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" ..\Drivers\STM32F3xx_HAL_Driver\Src\stm32f3xx_ll_usart.c -D STM32F303x8 -D USE_FULL_LL_DRIVER -o ..\EWARM\Debug\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling --debug --endian=little --cpu=Cortex-M4 -e --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I ..\EWARM/../Core/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\ -I ..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\ -I ..\EWARM/../Drivers/CMSIS/Include\ -On >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" ..\Drivers\STM32F3xx_HAL_Driver\Src\stm32f3xx_ll_usart.c -D STM32F303x8 -D USE_FULL_LL_DRIVER -D ENABLE_UART_DEBUGGING -o ..\EWARM\Printf\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling --debug --endian=little --cpu=Cortex-M4 -e --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I ..\EWARM/../Core/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\ -I ..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\ -I ..\EWARM/../Drivers/CMSIS/Include\ -On >> build-info.log

echo stm32f3xx_ll_utils >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" ..\Drivers\STM32F3xx_HAL_Driver\Src\stm32f3xx_ll_utils.c -D STM32F303x8 -D USE_FULL_LL_DRIVER -o ..\EWARM\Release\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir --debug --endian=little --cpu=Cortex-M4 -e --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I ..\EWARM/../Core/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\ -I ..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\ -I ..\EWARM/../Drivers/CMSIS/Include\ -Ohs >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" ..\Drivers\STM32F3xx_HAL_Driver\Src\stm32f3xx_ll_utils.c -D STM32F303x8 -D USE_FULL_LL_DRIVER -D ENABLE_UART_DEBUGGING -o ..\EWARM\Debug\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling --debug --endian=little --cpu=Cortex-M4 -e --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I ..\EWARM/../Core/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\ -I ..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\ -I ..\EWARM/../Drivers/CMSIS/Include\ -On >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" ..\Drivers\STM32F3xx_HAL_Driver\Src\stm32f3xx_ll_utils.c -D STM32F303x8 -D USE_FULL_LL_DRIVER -o ..\EWARM\Printf\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling --debug --endian=little --cpu=Cortex-M4 -e --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I ..\EWARM/../Core/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\ -I ..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\ -I ..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\ -I ..\EWARM/../Drivers/CMSIS/Include\ -On >> build-info.log

echo startup_stm32f303x8 >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iasmarm.exe" ..\EWARM\startup_stm32f303x8.s -O..\EWARM\Release\Obj\EWARM_18443280873093131863.dir -s+ -M"<>" -w+ -r --cpu Cortex-M4 --fpu VFPv4_sp >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iasmarm.exe" ..\EWARM\startup_stm32f303x8.s -O..\EWARM\Debug\Obj\EWARM_18443280873093131863.dir -s+ -M"<>" -w+ -r --cpu Cortex-M4 --fpu VFPv4_sp >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iasmarm.exe" ..\EWARM\startup_stm32f303x8.s -O..\EWARM\Printf\Obj\EWARM_18443280873093131863.dir -s+ -M"<>" -w+ -r --cpu Cortex-M4 --fpu VFPv4_sp  >> build-info.log

echo linker >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\ilinkarm.exe" ..\EWARM\Release\Obj\Core_13247989168731456611.dir\bsp.o ..\EWARM\Release\Obj\Core_13247989168731456611.dir\button_handler.o ..\EWARM\Release\Obj\Core_13247989168731456611.dir\delay_handler.o ..\EWARM\Release\Obj\Core_13247989168731456611.dir\gpio.o ..\EWARM\Release\Obj\Core_13247989168731456611.dir\logger.o ..\EWARM\Release\Obj\Core_13247989168731456611.dir\main.o ..\EWARM\Release\Obj\Core_13247989168731456611.dir\my_printf.o ..\EWARM\Release\Obj\Core_13247989168731456611.dir\pwm_handler.o ..\EWARM\Release\Obj\EWARM_18443280873093131863.dir\startup_stm32f303x8.o ..\EWARM\Release\Obj\Core_13247989168731456611.dir\stm32f3xx_it.o ..\EWARM\Release\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir\stm32f3xx_ll_dma.o ..\EWARM\Release\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir\stm32f3xx_ll_exti.o ..\EWARM\Release\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir\stm32f3xx_ll_gpio.o ..\EWARM\Release\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir\stm32f3xx_ll_rcc.o ..\EWARM\Release\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir\stm32f3xx_ll_tim.o ..\EWARM\Release\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir\stm32f3xx_ll_usart.o ..\EWARM\Release\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir\stm32f3xx_ll_utils.o ..\EWARM\Release\Obj\CMSIS_6603591812247902717.dir\system_stm32f3xx.o ..\EWARM\Release\Obj\Core_13247989168731456611.dir\thermistor_handler.o ..\EWARM\Release\Obj\Core_13247989168731456611.dir\tim.o --no_out_extension -o "..\EWARM\Release\Exe\CH-53K_LED_ Controller.out" --redirect _Printf=_PrintfFullNoMb --redirect _Scanf=_ScanfFullNoMb --map "..\EWARM\Release\List\CH-53K_LED_ Controller.map" --config ..\EWARM/stm32f303x8_flash.icf --semihosting --entry __iar_program_start --vfe --text_out locale --cpu=Cortex-M4 --fpu=VFPv4_sp >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\ilinkarm.exe" ..\EWARM\Debug\Obj\Core_13247989168731456611.dir\bsp.o ..\EWARM\Debug\Obj\Core_13247989168731456611.dir\button_handler.o ..\EWARM\Debug\Obj\Core_13247989168731456611.dir\delay_handler.o ..\EWARM\Debug\Obj\Core_13247989168731456611.dir\gpio.o ..\EWARM\Debug\Obj\Core_13247989168731456611.dir\logger.o ..\EWARM\Debug\Obj\Core_13247989168731456611.dir\main.o ..\EWARM\Debug\Obj\Core_13247989168731456611.dir\my_printf.o ..\EWARM\Debug\Obj\Core_13247989168731456611.dir\pwm_handler.o ..\EWARM\Debug\Obj\EWARM_18443280873093131863.dir\startup_stm32f303x8.o ..\EWARM\Debug\Obj\Core_13247989168731456611.dir\stm32f3xx_it.o ..\EWARM\Debug\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir\stm32f3xx_ll_dma.o ..\EWARM\Debug\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir\stm32f3xx_ll_exti.o ..\EWARM\Debug\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir\stm32f3xx_ll_gpio.o ..\EWARM\Debug\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir\stm32f3xx_ll_rcc.o ..\EWARM\Debug\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir\stm32f3xx_ll_tim.o ..\EWARM\Debug\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir\stm32f3xx_ll_usart.o ..\EWARM\Debug\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir\stm32f3xx_ll_utils.o ..\EWARM\Debug\Obj\CMSIS_6603591812247902717.dir\system_stm32f3xx.o ..\EWARM\Debug\Obj\Core_13247989168731456611.dir\thermistor_handler.o ..\EWARM\Debug\Obj\Core_13247989168731456611.dir\tim.o --no_out_extension -o "..\EWARM\Debug\Exe\CH-53K_LED_ Controller.out" --redirect _Printf=_PrintfFullNoMb --redirect _Scanf=_ScanfFullNoMb --map "..\EWARM\Debug\List\CH-53K_LED_ Controller.map" --config ..\EWARM/stm32f303x8_flash.icf --semihosting --entry __iar_program_start --vfe --text_out locale --cpu=Cortex-M4 --fpu=VFPv4_sp >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\ilinkarm.exe" ..\EWARM\Printf\Obj\Core_13247989168731456611.dir\bsp.o ..\EWARM\Printf\Obj\Core_13247989168731456611.dir\button_handler.o ..\EWARM\Printf\Obj\Core_13247989168731456611.dir\delay_handler.o ..\EWARM\Printf\Obj\Core_13247989168731456611.dir\gpio.o ..\EWARM\Printf\Obj\Core_13247989168731456611.dir\logger.o ..\EWARM\Printf\Obj\Core_13247989168731456611.dir\main.o ..\EWARM\Printf\Obj\Core_13247989168731456611.dir\my_printf.o ..\EWARM\Printf\Obj\Core_13247989168731456611.dir\pwm_handler.o ..\EWARM\Printf\Obj\EWARM_18443280873093131863.dir\startup_stm32f303x8.o ..\EWARM\Printf\Obj\Core_13247989168731456611.dir\stm32f3xx_it.o ..\EWARM\Printf\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir\stm32f3xx_ll_dma.o ..\EWARM\Printf\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir\stm32f3xx_ll_exti.o ..\EWARM\Printf\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir\stm32f3xx_ll_gpio.o ..\EWARM\Printf\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir\stm32f3xx_ll_rcc.o ..\EWARM\Printf\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir\stm32f3xx_ll_tim.o ..\EWARM\Printf\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir\stm32f3xx_ll_usart.o ..\EWARM\Printf\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir\stm32f3xx_ll_utils.o ..\EWARM\Printf\Obj\CMSIS_6603591812247902717.dir\system_stm32f3xx.o ..\EWARM\Printf\Obj\Core_13247989168731456611.dir\thermistor_handler.o ..\EWARM\Printf\Obj\Core_13247989168731456611.dir\tim.o ..\EWARM\Printf\Obj\Core_13247989168731456611.dir\usart.o --no_out_extension -o "..\EWARM\Printf\Exe\CH-53K_LED_ Controller.out" --redirect _Printf=_PrintfFullNoMb --redirect _Scanf=_ScanfFullNoMb --map "..\EWARM\Printf\List\CH-53K_LED_ Controller.map" --config ..\EWARM/stm32f303x8_flash.icf --semihosting --entry __iar_program_start --vfe --text_out locale --cpu=Cortex-M4 --fpu=VFPv4_sp >> build-info.log

echo elf >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\ielftool.exe" --ihex --verbose "..\EWARM\Release\Exe\CH-53K_LED_ Controller.out" "..\EWARM\Release\Exe\CH-53K_LED_ Controller.hex" >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\ielftool.exe" --ihex --verbose "..\EWARM\Debug\Exe\CH-53K_LED_ Controller.out" "..\EWARM\Debug\Exe\CH-53K_LED_ Controller.hex" >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\ielftool.exe" --ihex --verbose "..\EWARM\Printf\Exe\CH-53K_LED_ Controller.out" "..\EWARM\Printf\Exe\CH-53K_LED_ Controller.hex" >> build-info.log

grep "Errors:" build-info.log | grep -v ": none" > build-stats.log
grep "Warnings:" build-info.log | grep -v ": none" >> build-stats.log
