rm build-info.log
rm build-stats.log

echo ---RELEASE LOG--- > build-info.log
echo 01 >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" "..\Core\Src\my_printf.c" -D STM32F303x8 -D USE_HAL_DRIVER -o "..\EWARM\Release\Obj\Core_13247989168731456611.dir" --debug --endian=little --cpu=Cortex-M4 -e --warnings_are_errors --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I "..\EWARM/../Core/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\\" -I "..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\\" -I "..\EWARM/../Drivers/CMSIS/Include\\" -Ohs >> build-info.log
echo 02 >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" "..\Core\Src\stm32f3xx_it.c" -D STM32F303x8 -D USE_HAL_DRIVER -o "..\EWARM\Release\Obj\Core_13247989168731456611.dir" --debug --endian=little --cpu=Cortex-M4 -e --warnings_are_errors --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I "..\EWARM/../Core/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\\" -I "..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\\" -I "..\EWARM/../Drivers/CMSIS/Include\\" -Ohs >> build-info.log
echo 03 >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" "..\Core\Src\logger.c" -D STM32F303x8 -D USE_HAL_DRIVER -o "..\EWARM\Release\Obj\Core_13247989168731456611.dir" --debug --endian=little --cpu=Cortex-M4 -e --warnings_are_errors --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I "..\EWARM/../Core/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\\" -I "..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\\" -I "..\EWARM/../Drivers/CMSIS/Include\\" -Ohs >> build-info.log
echo 04 >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" "..\Core\Src\thermistor_handler.c" -D STM32F303x8 -D USE_HAL_DRIVER -o "..\EWARM\Release\Obj\Core_13247989168731456611.dir" --debug --endian=little --cpu=Cortex-M4 -e --warnings_are_errors --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I "..\EWARM/../Core/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\\" -I "..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\\" -I "..\EWARM/../Drivers/CMSIS/Include\\" -Ohs >> build-info.log
echo 05 >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" "..\Core\Src\bsp.c" -D STM32F303x8 -D USE_HAL_DRIVER -o "..\EWARM\Release\Obj\Core_13247989168731456611.dir" --debug --endian=little --cpu=Cortex-M4 -e --warnings_are_errors --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I "..\EWARM/../Core/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\\" -I "..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\\" -I "..\EWARM/../Drivers/CMSIS/Include\\" -Ohs >> build-info.log
echo 06 >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" "..\Core\Src\main.c" -D STM32F303x8 -D USE_HAL_DRIVER -o "..\EWARM\Release\Obj\Core_13247989168731456611.dir" --debug --endian=little --cpu=Cortex-M4 -e --warnings_are_errors --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I "..\EWARM/../Core/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\\" -I "..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\\" -I "..\EWARM/../Drivers/CMSIS/Include\\" -Ohs >> build-info.log
echo 07 >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" "..\Core\Src\button_handler.c" -D STM32F303x8 -D USE_HAL_DRIVER -o "..\EWARM\Release\Obj\Core_13247989168731456611.dir" --debug --endian=little --cpu=Cortex-M4 -e --warnings_are_errors --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I "..\EWARM/../Core/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\\" -I "..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\\" -I "..\EWARM/../Drivers/CMSIS/Include\\" -Ohs >> build-info.log
echo 08 >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" "..\Core\Src\pwm_handler.c" -D STM32F303x8 -D USE_HAL_DRIVER -o "..\EWARM\Release\Obj\Core_13247989168731456611.dir" --debug --endian=little --cpu=Cortex-M4 -e --warnings_are_errors --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I "..\EWARM/../Core/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\\" -I "..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\\" -I "..\EWARM/../Drivers/CMSIS/Include\\" -Ohs >> build-info.log
echo 09 >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" "..\Core\Src\tim.c" -D STM32F303x8 -D USE_HAL_DRIVER -o "..\EWARM\Release\Obj\Core_13247989168731456611.dir" --debug --endian=little --cpu=Cortex-M4 -e --warnings_are_errors --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I "..\EWARM/../Core/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\\" -I "..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\\" -I "..\EWARM/../Drivers/CMSIS/Include\\" -Ohs >> build-info.log
echo 10 >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" "..\Drivers\STM32F3xx_HAL_Driver\Src\stm32f3xx_hal_i2c_ex.c" -D STM32F303x8 -D USE_HAL_DRIVER -o "..\EWARM\Release\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir" --debug --endian=little --cpu=Cortex-M4 -e --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I "..\EWARM/../Core/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\\" -I "..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\\" -I "..\EWARM/../Drivers/CMSIS/Include\\" -Ohs >> build-info.log
echo 11 >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" "..\Core\Src\system_stm32f3xx.c" -D STM32F303x8 -D USE_HAL_DRIVER -o "..\EWARM\Release\Obj\CMSIS_6603591812247902717.dir" --debug --endian=little --cpu=Cortex-M4 -e --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I "..\EWARM/../Core/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\\" -I "..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\\" -I "..\EWARM/../Drivers/CMSIS/Include\\" -Ohs >> build-info.log
echo 12 >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" "..\Drivers\STM32F3xx_HAL_Driver\Src\stm32f3xx_hal_rcc_ex.c" -D STM32F303x8 -D USE_HAL_DRIVER -o "..\EWARM\Release\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir" --debug --endian=little --cpu=Cortex-M4 -e --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I "..\EWARM/../Core/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\\" -I "..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\\" -I "..\EWARM/../Drivers/CMSIS/Include\\" -Ohs >> build-info.log
echo 13 >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" "..\Drivers\STM32F3xx_HAL_Driver\Src\stm32f3xx_hal.c" -D STM32F303x8 -D USE_HAL_DRIVER -o "..\EWARM\Release\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir" --debug --endian=little --cpu=Cortex-M4 -e --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I "..\EWARM/../Core/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\\" -I "..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\\" -I "..\EWARM/../Drivers/CMSIS/Include\\" -Ohs >> build-info.log
echo 14 >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" "..\Drivers\STM32F3xx_HAL_Driver\Src\stm32f3xx_hal_pwr.c" -D STM32F303x8 -D USE_HAL_DRIVER -o "..\EWARM\Release\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir" --debug --endian=little --cpu=Cortex-M4 -e --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I "..\EWARM/../Core/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\\" -I "..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\\" -I "..\EWARM/../Drivers/CMSIS/Include\\" -Ohs >> build-info.log
echo 15 >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" "..\Drivers\STM32F3xx_HAL_Driver\Src\stm32f3xx_hal_dma.c" -D STM32F303x8 -D USE_HAL_DRIVER -o "..\EWARM\Release\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir" --debug --endian=little --cpu=Cortex-M4 -e --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I "..\EWARM/../Core/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\\" -I "..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\\" -I "..\EWARM/../Drivers/CMSIS/Include\\" -Ohs >> build-info.log
echo 16 >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" "..\Drivers\STM32F3xx_HAL_Driver\Src\stm32f3xx_hal_pwr_ex.c" -D STM32F303x8 -D USE_HAL_DRIVER -o "..\EWARM\Release\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir" --debug --endian=little --cpu=Cortex-M4 -e --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I "..\EWARM/../Core/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\\" -I "..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\\" -I "..\EWARM/../Drivers/CMSIS/Include\\" -Ohs >> build-info.log
echo 17 >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" "..\Drivers\STM32F3xx_HAL_Driver\Src\stm32f3xx_hal_flash.c" -D STM32F303x8 -D USE_HAL_DRIVER -o "..\EWARM\Release\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir" --debug --endian=little --cpu=Cortex-M4 -e --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I "..\EWARM/../Core/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\\" -I "..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\\" -I "..\EWARM/../Drivers/CMSIS/Include\\" -Ohs >> build-info.log
echo 18 >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" "..\Drivers\STM32F3xx_HAL_Driver\Src\stm32f3xx_hal_gpio.c" -D STM32F303x8 -D USE_HAL_DRIVER -o "..\EWARM\Release\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir" --debug --endian=little --cpu=Cortex-M4 -e --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I "..\EWARM/../Core/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\\" -I "..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\\" -I "..\EWARM/../Drivers/CMSIS/Include\\" -Ohs >> build-info.log
echo 19 >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iasmarm.exe" "..\EWARM\startup_stm32f303x8.s" "-O..\EWARM\Release\Obj\EWARM_18443280873093131863.dir" -s+ -M"<>" -w+ -r --cpu Cortex-M4 --fpu VFPv4_sp >> build-info.log
echo 20 >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" "..\Drivers\STM32F3xx_HAL_Driver\Src\stm32f3xx_hal_exti.c" -D STM32F303x8 -D USE_HAL_DRIVER -o "..\EWARM\Release\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir" --debug --endian=little --cpu=Cortex-M4 -e --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I "..\EWARM/../Core/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\\" -I "..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\\" -I "..\EWARM/../Drivers/CMSIS/Include\\" -Ohs >> build-info.log
echo 21 >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" "..\Drivers\STM32F3xx_HAL_Driver\Src\stm32f3xx_hal_cortex.c" -D STM32F303x8 -D USE_HAL_DRIVER -o "..\EWARM\Release\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir" --debug --endian=little --cpu=Cortex-M4 -e --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I "..\EWARM/../Core/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\\" -I "..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\\" -I "..\EWARM/../Drivers/CMSIS/Include\\" -Ohs >> build-info.log
echo 22 >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" "..\Drivers\STM32F3xx_HAL_Driver\Src\stm32f3xx_hal_uart_ex.c" -D STM32F303x8 -D USE_HAL_DRIVER -o "..\EWARM\Release\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir" --debug --endian=little --cpu=Cortex-M4 -e --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I "..\EWARM/../Core/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\\" -I "..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\\" -I "..\EWARM/../Drivers/CMSIS/Include\\" -Ohs >> build-info.log
echo 23 >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" "..\Drivers\STM32F3xx_HAL_Driver\Src\stm32f3xx_hal_flash_ex.c" -D STM32F303x8 -D USE_HAL_DRIVER -o "..\EWARM\Release\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir" --debug --endian=little --cpu=Cortex-M4 -e --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I "..\EWARM/../Core/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\\" -I "..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\\" -I "..\EWARM/../Drivers/CMSIS/Include\\" -Ohs >> build-info.log
echo 24 >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" "..\Drivers\STM32F3xx_HAL_Driver\Src\stm32f3xx_hal_rcc.c" -D STM32F303x8 -D USE_HAL_DRIVER -o "..\EWARM\Release\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir" --debug --endian=little --cpu=Cortex-M4 -e --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I "..\EWARM/../Core/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\\" -I "..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\\" -I "..\EWARM/../Drivers/CMSIS/Include\\" -Ohs >> build-info.log
echo 25 >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" "..\Drivers\STM32F3xx_HAL_Driver\Src\stm32f3xx_hal_tim_ex.c" -D STM32F303x8 -D USE_HAL_DRIVER -o "..\EWARM\Release\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir" --debug --endian=little --cpu=Cortex-M4 -e --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I "..\EWARM/../Core/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\\" -I "..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\\" -I "..\EWARM/../Drivers/CMSIS/Include\\" -Ohs >> build-info.log
echo 26 >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" "..\Drivers\STM32F3xx_HAL_Driver\Src\stm32f3xx_hal_uart.c" -D STM32F303x8 -D USE_HAL_DRIVER -o "..\EWARM\Release\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir" --debug --endian=little --cpu=Cortex-M4 -e --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I "..\EWARM/../Core/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\\" -I "..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\\" -I "..\EWARM/../Drivers/CMSIS/Include\\" -Ohs >> build-info.log
echo 27 >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" "..\Drivers\STM32F3xx_HAL_Driver\Src\stm32f3xx_hal_tim.c" -D STM32F303x8 -D USE_HAL_DRIVER -o "..\EWARM\Release\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir" --debug --endian=little --cpu=Cortex-M4 -e --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I "..\EWARM/../Core/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\\" -I "..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\\" -I "..\EWARM/../Drivers/CMSIS/Include\\" -Ohs >> build-info.log
echo 28 >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" "..\Drivers\STM32F3xx_HAL_Driver\Src\stm32f3xx_hal_i2c.c" -D STM32F303x8 -D USE_HAL_DRIVER -o "..\EWARM\Release\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir" --debug --endian=little --cpu=Cortex-M4 -e --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I "..\EWARM/../Core/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\\" -I "..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\\" -I "..\EWARM/../Drivers/CMSIS/Include\\" -Ohs >> build-info.log
echo 29 >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\ilinkarm.exe" "..\EWARM\Release\Obj\Core_13247989168731456611.dir\bsp.o" "..\EWARM\Release\Obj\Core_13247989168731456611.dir\button_handler.o" "..\EWARM\Release\Obj\Core_13247989168731456611.dir\delay_handler.o" "..\EWARM\Release\Obj\Core_13247989168731456611.dir\gpio.o" "..\EWARM\Release\Obj\Core_13247989168731456611.dir\logger.o" "..\EWARM\Release\Obj\Core_13247989168731456611.dir\main.o" "..\EWARM\Release\Obj\Core_13247989168731456611.dir\my_printf.o" "..\EWARM\Release\Obj\Core_13247989168731456611.dir\pwm_handler.o" "..\EWARM\Release\Obj\EWARM_18443280873093131863.dir\startup_stm32f303x8.o" "..\EWARM\Release\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir\stm32f3xx_hal.o" "..\EWARM\Release\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir\stm32f3xx_hal_cortex.o" "..\EWARM\Release\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir\stm32f3xx_hal_dma.o" "..\EWARM\Release\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir\stm32f3xx_hal_exti.o" "..\EWARM\Release\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir\stm32f3xx_hal_flash.o" "..\EWARM\Release\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir\stm32f3xx_hal_flash_ex.o" "..\EWARM\Release\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir\stm32f3xx_hal_gpio.o" "..\EWARM\Release\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir\stm32f3xx_hal_i2c.o" "..\EWARM\Release\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir\stm32f3xx_hal_i2c_ex.o" "..\EWARM\Release\Obj\Core_13247989168731456611.dir\stm32f3xx_hal_msp.o" "..\EWARM\Release\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir\stm32f3xx_hal_pwr.o" "..\EWARM\Release\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir\stm32f3xx_hal_pwr_ex.o" "..\EWARM\Release\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir\stm32f3xx_hal_rcc.o" "..\EWARM\Release\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir\stm32f3xx_hal_rcc_ex.o" "..\EWARM\Release\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir\stm32f3xx_hal_tim.o" "..\EWARM\Release\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir\stm32f3xx_hal_tim_ex.o" "..\EWARM\Release\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir\stm32f3xx_hal_uart.o" "..\EWARM\Release\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir\stm32f3xx_hal_uart_ex.o" "..\EWARM\Release\Obj\Core_13247989168731456611.dir\stm32f3xx_it.o" "..\EWARM\Release\Obj\CMSIS_6603591812247902717.dir\system_stm32f3xx.o" "..\EWARM\Release\Obj\Core_13247989168731456611.dir\thermistor_handler.o" "..\EWARM\Release\Obj\Core_13247989168731456611.dir\tim.o" --no_out_extension -o "..\EWARM\Release\Exe\CH-53K_LED_ Controller.out" --redirect _Printf=_PrintfFullNoMb --redirect _Scanf=_ScanfFullNoMb --map "..\EWARM\Release\List\CH-53K_LED_ Controller.map" --config "..\EWARM/stm32f303x8_flash.icf" --semihosting --entry __iar_program_start --vfe --text_out locale --cpu=Cortex-M4 --fpu=VFPv4_sp >> build-info.log
echo 30 >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\ielftool.exe" --ihex --verbose "..\EWARM\Release\Exe\CH-53K_LED_ Controller.out" "..\EWARM\Release\Exe\CH-53K_LED_ Controller.hex" >> build-info.log

echo ---DEBUG LOG--- >> build-info.log
echo 31 >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" "..\Core\Src\my_printf.c" -D STM32F303x8 -D USE_HAL_DRIVER -o "..\EWARM\Debug\Obj\Core_13247989168731456611.dir" --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling --debug --endian=little --cpu=Cortex-M4 -e --warnings_are_errors --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I "..\EWARM/../Core/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\\" -I "..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\\" -I "..\EWARM/../Drivers/CMSIS/Include\\" -On --require_prototypes >> build-info.log
echo 32 >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" "..\Core\Src\button_handler.c" -D STM32F303x8 -D USE_HAL_DRIVER -o "..\EWARM\Debug\Obj\Core_13247989168731456611.dir" --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling --debug --endian=little --cpu=Cortex-M4 -e --warnings_are_errors --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I "..\EWARM/../Core/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\\" -I "..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\\" -I "..\EWARM/../Drivers/CMSIS/Include\\" -On --require_prototypes >> build-info.log
echo 33 >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" "..\Core\Src\stm32f3xx_it.c" -D STM32F303x8 -D USE_HAL_DRIVER -o "..\EWARM\Debug\Obj\Core_13247989168731456611.dir" --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling --debug --endian=little --cpu=Cortex-M4 -e --warnings_are_errors --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I "..\EWARM/../Core/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\\" -I "..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\\" -I "..\EWARM/../Drivers/CMSIS/Include\\" -On --require_prototypes >> build-info.log
echo 34 >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" "..\Core\Src\stm32f3xx_hal_msp.c" -D STM32F303x8 -D USE_HAL_DRIVER -o "..\EWARM\Debug\Obj\Core_13247989168731456611.dir" --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling --debug --endian=little --cpu=Cortex-M4 -e --warnings_are_errors --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I "..\EWARM/../Core/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\\" -I "..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\\" -I "..\EWARM/../Drivers/CMSIS/Include\\" -On --require_prototypes >> build-info.log
echo 35 >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" "..\Core\Src\gpio.c" -D STM32F303x8 -D USE_HAL_DRIVER -o "..\EWARM\Debug\Obj\Core_13247989168731456611.dir" --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling --debug --endian=little --cpu=Cortex-M4 -e --warnings_are_errors --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I "..\EWARM/../Core/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\\" -I "..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\\" -I "..\EWARM/../Drivers/CMSIS/Include\\" -On --require_prototypes >> build-info.log
echo 36 >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" "..\Core\Src\logger.c" -D STM32F303x8 -D USE_HAL_DRIVER -o "..\EWARM\Debug\Obj\Core_13247989168731456611.dir" --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling --debug --endian=little --cpu=Cortex-M4 -e --warnings_are_errors --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I "..\EWARM/../Core/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\\" -I "..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\\" -I "..\EWARM/../Drivers/CMSIS/Include\\" -On --require_prototypes >> build-info.log
echo 37 >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" "..\Core\Src\thermistor_handler.c" -D STM32F303x8 -D USE_HAL_DRIVER -o "..\EWARM\Debug\Obj\Core_13247989168731456611.dir" --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling --debug --endian=little --cpu=Cortex-M4 -e --warnings_are_errors --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I "..\EWARM/../Core/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\\" -I "..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\\" -I "..\EWARM/../Drivers/CMSIS/Include\\" -On --require_prototypes >> build-info.log
echo 38 >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" "..\Core\Src\delay_handler.c" -D STM32F303x8 -D USE_HAL_DRIVER -o "..\EWARM\Debug\Obj\Core_13247989168731456611.dir" --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling --debug --endian=little --cpu=Cortex-M4 -e --warnings_are_errors --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I "..\EWARM/../Core/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\\" -I "..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\\" -I "..\EWARM/../Drivers/CMSIS/Include\\" -On --require_prototypes >> build-info.log
echo 39 >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" "..\Core\Src\bsp.c" -D STM32F303x8 -D USE_HAL_DRIVER -o "..\EWARM\Debug\Obj\Core_13247989168731456611.dir" --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling --debug --endian=little --cpu=Cortex-M4 -e --warnings_are_errors --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I "..\EWARM/../Core/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\\" -I "..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\\" -I "..\EWARM/../Drivers/CMSIS/Include\\" -On --require_prototypes >> build-info.log
echo 40 >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" "..\Core\Src\pwm_handler.c" -D STM32F303x8 -D USE_HAL_DRIVER -o "..\EWARM\Debug\Obj\Core_13247989168731456611.dir" --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling --debug --endian=little --cpu=Cortex-M4 -e --warnings_are_errors --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I "..\EWARM/../Core/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\\" -I "..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\\" -I "..\EWARM/../Drivers/CMSIS/Include\\" -On --require_prototypes >> build-info.log
echo 41 >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" "..\Core\Src\tim.c" -D STM32F303x8 -D USE_HAL_DRIVER -o "..\EWARM\Debug\Obj\Core_13247989168731456611.dir" --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling --debug --endian=little --cpu=Cortex-M4 -e --warnings_are_errors --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I "..\EWARM/../Core/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\\" -I "..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\\" -I "..\EWARM/../Drivers/CMSIS/Include\\" -On --require_prototypes >> build-info.log
echo 42 >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" "..\Drivers\STM32F3xx_HAL_Driver\Src\stm32f3xx_hal_pwr_ex.c" -D STM32F303x8 -D USE_HAL_DRIVER -o "..\EWARM\Debug\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir" --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling --debug --endian=little --cpu=Cortex-M4 -e --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I "..\EWARM/../Core/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\\" -I "..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\\" -I "..\EWARM/../Drivers/CMSIS/Include\\" -On >> build-info.log
echo 43 >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" "..\Core\Src\main.c" -D STM32F303x8 -D USE_HAL_DRIVER -o "..\EWARM\Debug\Obj\Core_13247989168731456611.dir" --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling --debug --endian=little --cpu=Cortex-M4 -e --warnings_are_errors --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I "..\EWARM/../Core/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\\" -I "..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\\" -I "..\EWARM/../Drivers/CMSIS/Include\\" -On --require_prototypes >> build-info.log
echo 44 >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" "..\Drivers\STM32F3xx_HAL_Driver\Src\stm32f3xx_hal_pwr.c" -D STM32F303x8 -D USE_HAL_DRIVER -o "..\EWARM\Debug\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir" --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling --debug --endian=little --cpu=Cortex-M4 -e --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I "..\EWARM/../Core/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\\" -I "..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\\" -I "..\EWARM/../Drivers/CMSIS/Include\\" -On >> build-info.log
echo 45 >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" "..\Core\Src\system_stm32f3xx.c" -D STM32F303x8 -D USE_HAL_DRIVER -o "..\EWARM\Debug\Obj\CMSIS_6603591812247902717.dir" --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling --debug --endian=little --cpu=Cortex-M4 -e --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I "..\EWARM/../Core/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\\" -I "..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\\" -I "..\EWARM/../Drivers/CMSIS/Include\\" -On >> build-info.log
echo 46 >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" "..\Drivers\STM32F3xx_HAL_Driver\Src\stm32f3xx_hal_i2c_ex.c" -D STM32F303x8 -D USE_HAL_DRIVER -o "..\EWARM\Debug\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir" --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling --debug --endian=little --cpu=Cortex-M4 -e --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I "..\EWARM/../Core/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\\" -I "..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\\" -I "..\EWARM/../Drivers/CMSIS/Include\\" -On >> build-info.log
echo 47 >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" "..\Drivers\STM32F3xx_HAL_Driver\Src\stm32f3xx_hal_cortex.c" -D STM32F303x8 -D USE_HAL_DRIVER -o "..\EWARM\Debug\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir" --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling --debug --endian=little --cpu=Cortex-M4 -e --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I "..\EWARM/../Core/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\\" -I "..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\\" -I "..\EWARM/../Drivers/CMSIS/Include\\" -On >> build-info.log
echo 48 >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" "..\Drivers\STM32F3xx_HAL_Driver\Src\stm32f3xx_hal_uart_ex.c" -D STM32F303x8 -D USE_HAL_DRIVER -o "..\EWARM\Debug\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir" --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling --debug --endian=little --cpu=Cortex-M4 -e --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I "..\EWARM/../Core/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\\" -I "..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\\" -I "..\EWARM/../Drivers/CMSIS/Include\\" -On >> build-info.log
echo 49 >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" "..\Drivers\STM32F3xx_HAL_Driver\Src\stm32f3xx_hal.c" -D STM32F303x8 -D USE_HAL_DRIVER -o "..\EWARM\Debug\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir" --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling --debug --endian=little --cpu=Cortex-M4 -e --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I "..\EWARM/../Core/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\\" -I "..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\\" -I "..\EWARM/../Drivers/CMSIS/Include\\" -On >> build-info.log
echo 50 >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" "..\Drivers\STM32F3xx_HAL_Driver\Src\stm32f3xx_hal_gpio.c" -D STM32F303x8 -D USE_HAL_DRIVER -o "..\EWARM\Debug\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir" --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling --debug --endian=little --cpu=Cortex-M4 -e --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I "..\EWARM/../Core/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\\" -I "..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\\" -I "..\EWARM/../Drivers/CMSIS/Include\\" -On >> build-info.log
echo 51 >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" "..\Drivers\STM32F3xx_HAL_Driver\Src\stm32f3xx_hal_exti.c" -D STM32F303x8 -D USE_HAL_DRIVER -o "..\EWARM\Debug\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir" --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling --debug --endian=little --cpu=Cortex-M4 -e --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I "..\EWARM/../Core/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\\" -I "..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\\" -I "..\EWARM/../Drivers/CMSIS/Include\\" -On >> build-info.log
echo 52 >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iasmarm.exe" "..\EWARM\startup_stm32f303x8.s" "-O..\EWARM\Debug\Obj\EWARM_18443280873093131863.dir" -s+ -M"<>" -w+ -r --cpu Cortex-M4 --fpu VFPv4_sp >> build-info.log
echo 53 >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" "..\Drivers\STM32F3xx_HAL_Driver\Src\stm32f3xx_hal_flash.c" -D STM32F303x8 -D USE_HAL_DRIVER -o "..\EWARM\Debug\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir" --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling --debug --endian=little --cpu=Cortex-M4 -e --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I "..\EWARM/../Core/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\\" -I "..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\\" -I "..\EWARM/../Drivers/CMSIS/Include\\" -On >> build-info.log
echo 54 >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" "..\Drivers\STM32F3xx_HAL_Driver\Src\stm32f3xx_hal_rcc.c" -D STM32F303x8 -D USE_HAL_DRIVER -o "..\EWARM\Debug\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir" --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling --debug --endian=little --cpu=Cortex-M4 -e --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I "..\EWARM/../Core/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\\" -I "..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\\" -I "..\EWARM/../Drivers/CMSIS/Include\\" -On >> build-info.log
echo 55 >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" "..\Drivers\STM32F3xx_HAL_Driver\Src\stm32f3xx_hal_rcc_ex.c" -D STM32F303x8 -D USE_HAL_DRIVER -o "..\EWARM\Debug\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir" --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling --debug --endian=little --cpu=Cortex-M4 -e --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I "..\EWARM/../Core/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\\" -I "..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\\" -I "..\EWARM/../Drivers/CMSIS/Include\\" -On >> build-info.log
echo 56 >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" "..\Drivers\STM32F3xx_HAL_Driver\Src\stm32f3xx_hal_flash_ex.c" -D STM32F303x8 -D USE_HAL_DRIVER -o "..\EWARM\Debug\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir" --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling --debug --endian=little --cpu=Cortex-M4 -e --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I "..\EWARM/../Core/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\\" -I "..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\\" -I "..\EWARM/../Drivers/CMSIS/Include\\" -On >> build-info.log
echo 57 >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" "..\Drivers\STM32F3xx_HAL_Driver\Src\stm32f3xx_hal_dma.c" -D STM32F303x8 -D USE_HAL_DRIVER -o "..\EWARM\Debug\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir" --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling --debug --endian=little --cpu=Cortex-M4 -e --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I "..\EWARM/../Core/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\\" -I "..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\\" -I "..\EWARM/../Drivers/CMSIS/Include\\" -On >> build-info.log
echo 58 >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" "..\Drivers\STM32F3xx_HAL_Driver\Src\stm32f3xx_hal_tim_ex.c" -D STM32F303x8 -D USE_HAL_DRIVER -o "..\EWARM\Debug\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir" --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling --debug --endian=little --cpu=Cortex-M4 -e --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I "..\EWARM/../Core/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\\" -I "..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\\" -I "..\EWARM/../Drivers/CMSIS/Include\\" -On >> build-info.log
echo 59 >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" "..\Drivers\STM32F3xx_HAL_Driver\Src\stm32f3xx_hal_uart.c" -D STM32F303x8 -D USE_HAL_DRIVER -o "..\EWARM\Debug\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir" --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling --debug --endian=little --cpu=Cortex-M4 -e --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I "..\EWARM/../Core/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\\" -I "..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\\" -I "..\EWARM/../Drivers/CMSIS/Include\\" -On >> build-info.log
echo 60 >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" "..\Drivers\STM32F3xx_HAL_Driver\Src\stm32f3xx_hal_i2c.c" -D STM32F303x8 -D USE_HAL_DRIVER -o "..\EWARM\Debug\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir" --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling --debug --endian=little --cpu=Cortex-M4 -e --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I "..\EWARM/../Core/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\\" -I "..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\\" -I "..\EWARM/../Drivers/CMSIS/Include\\" -On >> build-info.log
echo 61 >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\iccarm.exe" "..\Drivers\STM32F3xx_HAL_Driver\Src\stm32f3xx_hal_tim.c" -D STM32F303x8 -D USE_HAL_DRIVER -o "..\EWARM\Debug\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir" --no_cse --no_unroll --no_inline --no_code_motion --no_tbaa --no_clustering --no_scheduling --debug --endian=little --cpu=Cortex-M4 -e --fpu=VFPv4_sp --dlib_config "C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\inc\c\DLib_Config_Full.h" -I "..\EWARM/../Core/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc\\" -I "..\EWARM/../Drivers/STM32F3xx_HAL_Driver/Inc/Legacy\\" -I "..\EWARM/../Drivers/CMSIS/Device/ST/STM32F3xx/Include\\" -I "..\EWARM/../Drivers/CMSIS/Include\\" -On >> build-info.log
echo 62 >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\ilinkarm.exe" "..\EWARM\Debug\Obj\Core_13247989168731456611.dir\bsp.o" "..\EWARM\Debug\Obj\Core_13247989168731456611.dir\button_handler.o" "..\EWARM\Debug\Obj\Core_13247989168731456611.dir\delay_handler.o" "..\EWARM\Debug\Obj\Core_13247989168731456611.dir\gpio.o" "..\EWARM\Debug\Obj\Core_13247989168731456611.dir\logger.o" "..\EWARM\Debug\Obj\Core_13247989168731456611.dir\main.o" "..\EWARM\Debug\Obj\Core_13247989168731456611.dir\my_printf.o" "..\EWARM\Debug\Obj\Core_13247989168731456611.dir\pwm_handler.o" "..\EWARM\Debug\Obj\EWARM_18443280873093131863.dir\startup_stm32f303x8.o" "..\EWARM\Debug\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir\stm32f3xx_hal.o" "..\EWARM\Debug\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir\stm32f3xx_hal_cortex.o" "..\EWARM\Debug\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir\stm32f3xx_hal_dma.o" "..\EWARM\Debug\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir\stm32f3xx_hal_exti.o" "..\EWARM\Debug\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir\stm32f3xx_hal_flash.o" "..\EWARM\Debug\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir\stm32f3xx_hal_flash_ex.o" "..\EWARM\Debug\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir\stm32f3xx_hal_gpio.o" "..\EWARM\Debug\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir\stm32f3xx_hal_i2c.o" "..\EWARM\Debug\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir\stm32f3xx_hal_i2c_ex.o" "..\EWARM\Debug\Obj\Core_13247989168731456611.dir\stm32f3xx_hal_msp.o" "..\EWARM\Debug\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir\stm32f3xx_hal_pwr.o" "..\EWARM\Debug\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir\stm32f3xx_hal_pwr_ex.o" "..\EWARM\Debug\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir\stm32f3xx_hal_rcc.o" "..\EWARM\Debug\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir\stm32f3xx_hal_rcc_ex.o" "..\EWARM\Debug\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir\stm32f3xx_hal_tim.o" "..\EWARM\Debug\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir\stm32f3xx_hal_tim_ex.o" "..\EWARM\Debug\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir\stm32f3xx_hal_uart.o" "..\EWARM\Debug\Obj\STM32F3xx_HAL_Driver_12277016440933995095.dir\stm32f3xx_hal_uart_ex.o" "..\EWARM\Debug\Obj\Core_13247989168731456611.dir\stm32f3xx_it.o" "..\EWARM\Debug\Obj\CMSIS_6603591812247902717.dir\system_stm32f3xx.o" "..\EWARM\Debug\Obj\Core_13247989168731456611.dir\thermistor_handler.o" "..\EWARM\Debug\Obj\Core_13247989168731456611.dir\tim.o" --no_out_extension -o "..\EWARM\Debug\Exe\CH-53K_LED_ Controller.out" --redirect _Printf=_PrintfFullNoMb --redirect _Scanf=_ScanfFullNoMb --map "..\EWARM\Debug\List\CH-53K_LED_ Controller.map" --config "..\EWARM/stm32f303x8_flash.icf" --semihosting --entry __iar_program_start --vfe --text_out locale --cpu=Cortex-M4 --fpu=VFPv4_sp >> build-info.log
echo 63 >> build-info.log
"C:\Programs\IAR Systems\Embedded Workbench 9.2\arm\bin\ielftool.exe" --ihex --verbose "..\EWARM\Debug\Exe\CH-53K_LED_ Controller.out" "..\EWARM\Debug\Exe\CH-53K_LED_ Controller.hex" >> build-info.log

grep "Errors:" build-info.log | grep -v ": none" > build-stats.log
grep "Warnings:" build-info.log | grep -v ": none" >> build-stats.log
